### PR TITLE
Auto redirect to https in prod

### PR DESCRIPTION
**Pull request by makinde**
We've got CloudFlare up and we want all requests to be over https in prod

### CODE REVIEW

**Comment by astonm** [comment]
We should use the idiomatic node.js production vs. development name here, `NODE_ENV`: http://www.hacksparrow.com/running-express-js-in-production-mode.html

**Comment by makinde** [comment]
@astonm updated. Unclear if it's cool to have a handler inside the config function, lmk if that seems off.

**Comment by astonm** [comment]
Looks fine syntactically / idiomatically, but I just learned that `app.configure` doesn't exist in express v4. https://github.com/expressjs/express/wiki/Migrating-from-3.x-to-4.x#appconfigure

Here's what I get when I run this branch locally:

```
app.configure('production', function() {
    ^

TypeError: app.configure is not a function
```

**Comment by makinde** [comment]
Lol, k, will change






On Wed, Mar 2, 2016 at 5:23 PM -0800, "Aston Motes" <notifications@github.com> wrote:












Looks fine syntactically / idiomatically, but I just learned that app.configure doesn't exist in express v4. https://github.com/expressjs/express/wiki/Migrating-from-3.x-to-4.x#appconfigure



Here's what I get when I run this branch locally:

app.configure('production', function() {
    ^

TypeError: app.configure is not a function

**Pull request merged**
